### ISSUE TITLE
Data Processing/Process Images: Activity Heat map- 0s different than NA

### ISSUE THREAD

**Issue by rsalom** [pantheracorp/PantheraIDS_Features#7]
To be able to see in the Activity Heat Map the zeros as white squares instead of NA. Keep NA just for empty areas, where the station was either not set or already retrieved from the field.

**Comment by RossPitman** [comment]
So we've been playing around with this idea, and came to the conclusion that we've somewhat mislead users in how this heatmap is generated, and what its purpose is. The heatmap is only to be used to identify when cameras captured images on a particular day. Historically, we've described this heatmap as being part of the cameras active process, which was actually incorrect. This is evident in this issue request, in that NA values and 0 values should mean something--as they do in the cameras active. But, for this heatmap, NA's or O's imply the same thing, that being the fact that no image was captured by a particular camera on a particular day. The distinction is quite important because the data informing the heatmap has nothing to do with the cameras active, and so it cannot distinuigh when a camera was setup or taken down, or not active in the field. Therefore, instead of changing the heatmap (as requested), we are going to redefine the heatmap and what it actually means. This will include changing the tab name from "Camera Activity Heatmap" to "Captures Heatmap", and updating the help files.
